### PR TITLE
Allow user-defined tokens in ivyLayout pattern.

### PR DESCRIPTION
**Pull request by AurelienLourot**
This PR adds the possibility to use user-defined ivy tokens in the path where `ivy.xml` will be pushed to Artifactory. The DSL looks like

```
artifactory {
    publish {
        repository {
            ivy {
                ivyLayout = "[organization]/[module]/[myGreatToken]/[revision]/ivy-[revision].xml"
            }
        }
    }
}

// ...

publishing.publications.create("Ivy_myGreatPublication", IvyPublication) {
    organisation = "com.tomtom"
    descriptor.extraInfo("dummy", "myGreatToken", "myGreatValue")
}
```

`dummy` is a so-called "namespace", that isn't taken into account when resolving the layout. The DSL forces us to provide one though, see https://docs.gradle.org/2.7/javadoc/org/gradle/api/publish/ivy/IvyModuleDescriptorSpec.html .

As a side effect, the produced `ivy.xml` contains:
```
  <info organisation="com.tomtom" module="myGreatModule" revision="1.0.2-SNAPSHOT" status="snapshot" publication="20150921173700">
    <ns:myGreatToken xmlns:ns="dummy">myGreatValue</ns:myGreatToken>
  </info>
```

This PR is a "private" one intended to TomTom for internal review, before we submit it to JFrog.

### CODE REVIEW

**Comment by AurelienLourot** [comment]
@maikelvdh, @ffung, I'm sure you want to review this :)

**Comment by maikelvdh** [comment]
Reading http://ant.apache.org/ivy/history/trunk/concept.html#extra we should be able to produce the ivy.xml more like: 
<info organisation="com.tomtom" module="myGreatModule" e:myGreatToken="myGreatValue" revision="1.0.2-SNAPSHOT" status="snapshot" publication="20150921173700" />

**Comment by maikelvdh** [comment]
LGTM :+1:

**Comment by AurelienLourot** [comment]
@maikelvdh, regarding `e:myGreatToken` you're right and as you can see in this [example](https://github.com/JFrogDev/project-examples/blob/master/gradle-examples/gradle-example-publish/build.gradle) from JFrog, this can only be achieved by using `withXml`. I prefer to use what Gradle offers natively though. But it's a good point as using that, I could have probably implemented this feature for Gradle 1.8 too.

**Comment by AurelienLourot** [comment]
I will now decline this PR as it has been superseded by https://github.com/JFrogDev/build-info/pull/57 .

**Pull request closed without merging**
